### ISSUE TITLE
I can't launch Toonstruck

### ISSUE THREAD

**Issue by NerosTie** [libretro-mirrors/scummvm#93]
When I want to launch Toonstruck, I have an error : ```unable to locate the 'toon.dat' engine data file``` then ```Error running game: Unkown error```. 

Toonstruck works with the normal Scummvm 2.0 app and I have no issues with others games in Retroarch.

**Comment by i30817** [comment]
toon.dat is on the scummvm repository, although i can understand the problem. Apparently a older version of the engine used these extracted strings without a fallback of parsing them directly. Or your scummvm 2.0 app installed them on a place it finds them..

https://github.com/scummvm/scummvm/tree/master/dists/engine-data

There are also other important files there. Especially kyra.dat

**Comment by NerosTie** [comment]
Ok I see. For the libretro we need to add these engines manually in a extra folder (and add this path in ```Options -> Paths -> Extra Path:```) and it works.

It should be specified in the docs.

**Comment by NelsonRosenberg** [comment]
I agree that it would be nice if this info was in the README as it is not something you need to do in standalone scummvm.

**Comment by i30817** [comment]
I place them on the game dir but essentially correct @NerosTie .

**Comment by NerosTie** [comment]
Fixed

**Comment by i30817** [comment]
> Fixed

I use this these days: https://github.com/i30817/libretro-mkscumm

Did the program myself to be able to scan all versions of the game as recognized by the actual scummvm scanner (not the RetroArch scanner, the one you can run if you run the core standalone), with correct names (otherwise impossible because the names scummvm uses have illegal filesystem characters for windows and Linux).

As a bonus it verifies some things in the scummvm.ini file the core uses are filled in, like Kyra.dat among others and warns if they're not. And more importantly it removes the annoying 'create .scummvm files' step.
