### ISSUE TITLE
"Game data not found" when  loading .scummvm file

### ISSUE THREAD

**Issue by jeweloper** [libretro-mirrors/scummvm#94]
At least since June there are the issue that you could not load a .scummvm file anymore, if it is not in the game directory (see open issue #71).
Are there any plans to fix this issue?
If not, is there another option to load games from e.g. emulationstation and do not put all the game files in one directory.
My current structure is:
1. Directory with all .scummvm files (read by emulationstation). ~/emulationstation/scummvm/
2. Data directory contains one sub directory for every single game. ~/roms/scummvm/{game-1}{game-2}...

Thx.

Platform: RPI2
System: Arch Linux ARM
Version: libretro-scummvm 84203-1

**Comment by RobLoach** [comment]
What's in your `.scummvm` file?

**Comment by jeweloper** [comment]
The files contain the game id. There is no problem to launch a game with these .scummvm files, if they are located within the game path.
It does not work, if they are located outside the game path. (Error message is the same mentioned in #71).

My current workaround is, to place my .scummvm files in both: In the emulationstation rom directory (to aggregate by emulationstation) and a copy in the scummvm game directory.
In emulationstation es_systems.cfg I now refer to a self written script to run retroarch+libretro-scummvm. These script dynamically builds the correct path to the scummvm file located in the games directory.

**Comment by Ferk** [comment]
It makes sense to require the .scummvm to be in the game directory, because scummvm cannot know otherwise what's the path to the game for a game that has not been previously added.

What you can do in your particular case is add to the content of the file an additional path option (eg: ``--path='PATH_TO_THE_GAME'  ID_OF_THE_GAME``, written inside the .scummvm file) I believe this would work, the content of the file is appended to the list of arguments that scummvm would otherwise process, so the path that's automatically set by the core will be overridden by the path option you set inside the file, since it's loaded later.

**Comment by jeweloper** [comment]
Thx. What worked for me: `-p 'PATH_TO_THE_GAME' ID_OF_THE_GAME`
Is there also a option/parameter to set the Save Path?

**Comment by Ferk** [comment]
There is a ``--savepath=PATH`` option from the official scummvm, but this might not work for the retroarch core.

**Comment by jeweloper** [comment]
Thx for your answer.
Because my primary question was answered, I will close this issue.

**Comment by RobLoach** [comment]
Does the ScummVM Core change the `--savepath` in ScummVM to the `Savefile` directory?

**Comment by jeweloper** [comment]
No, it does not.
But anyway, I don't like the way to write absolute path information into my `.scummvm` files.
I will continue to use my workaround.
